# Generated by Django 3.1.7 on 2021-03-29 21:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='human',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.human'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='land',
            name='lat',
            field=models.FloatField(db_index=True, default=0, help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='land',
            name='lng',
            field=models.FloatField(db_index=True, default=0, help_text='Longitude'),
        ),
        migrations.AlterField(
            model_name='land',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='nft',
            name='land',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.land'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
