# Generated by Django 3.1.7 on 2021-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210329_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='nft_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unminted'), (2, 'Claimed'), (3, 'For sale')], default=1),
        ),
    ]
