# Generated by Django 3.1.7 on 2021-04-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210330_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='img',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='human',
            name='username_unique',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
