# Generated by Django 3.1.7 on 2021-04-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210402_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='address',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nft',
            name='listing_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='story',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
