# Generated by Django 3.1.7 on 2021-04-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210402_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='password',
        ),
        migrations.RemoveField(
            model_name='human',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='human',
            name='profile_image',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='address',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
