# Generated by Django 3.1.7 on 2021-04-05 01:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210403_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('address', models.CharField(max_length=128)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.human')),
            ],
        ),
    ]
